COUNTRIES = [
    'AUSTRALIA', 'AUSTRIA', 'BELGIUM', 'CANADA', 'CHILE', 'COLOMBIA',
    'COSTA RICA', 'DENMARK', 'ESTONIA', 'FINLAND', 'FRANCE', 'GERMANY',
    'GREECE', 'ICELAND', 'IRELAND', 'ISRAEL', 'ITALY', 'JAPAN', 'SOUTH KOREA',
    'LUXEMBOURG', 'MEXICO', 'NETHERLANDS', 'NEW ZEALAND', 'NORWAY',
    'POLAND', 'PORTUGAL', 'SPAIN', 'SWEDEN', 'SWITZERLAND', 'TURKEY',
    'UNITED KINGDOM', 'UNITED STATES', 'CHINA'
]
