COUNTRIES = [
    # North America
    'UNITED STATES', 'CANADA', 'MEXICO',
    # South America
    'CHILE', 'COSTA RICA', 'COLOMBIA',
    # Asia
    'SINGAPORE', 'CHINA', 'JAPAN', 'SOUTH KOREA', 'THAILAND',
    'TAIWAN',
    # UE
    'NORWAY', 'SWITZERLAND', 'GERMANY', 'DENMARK', 'NETHERLANDS',
    'IRELAND', 'FINLAND', 'SWEDEN', 'UNITED KINGDOM', 'LUXEMBOURG',
    'FRANCE', 'BELGIUM', 'AUSTRIA', 'SLOVENIA', 'ITALY', 'POLAND',
    'SPAIN', 'CZECHIA', 'GREECE', 'ESTONIA', 'PORTUGAL',
    # Oceania
    'AUSTRALIA', 'NEW ZEALAND',
    # Middle East
    'TURKEY', 'ISRAEL', 'QATAR'
]